In [4]:
import pandas as pd

In [3]:
log = pd.read_csv('./raw/LOG.csv')
print(log.shape)
log.head(2)

C:\Users\amore\AppData\Local\Temp\ipykernel_20104\1845494227.py:1: DtypeWarning: Columns (27,28,29,55,65,69,71,84) have mixed types. Specify dtype option on import or set low_memory=False.
  log = pd.read_csv('./raw/LOG.csv')

(3668294, 99)

,STND_YMD,SITE_ID,WEB_APP_CL_CD,LOG_SEQ,LOG_DTTM,GOOGLE_CID,SESS_ID,ADID,INCS_NO,SITE_MBR_ID,...,DVCE_MKT_NM,DVCE_OPRT_NM,DVCE_OPRT_VER,NEW_VISIT_YN,STORE_CD,INVN_ST_YN,SESS_SN_STAY_TIME,EXPS_RSLT_LIST,LIST_TP_NM,ETL_PROC_DTTM
0,2024-11-06,UA-110770460-3,WEB,861c6fa067ce9752003b89d3241b51367461c457958400...,2024-11-06 22:22:06.499,2049144370.1730898977,2049144370.17308989771730898977,NaN,f6eec8e63cee2cf90165c6b3f68c1285d9ffedf7f8e134...,d8d5b1d15ce86752f1f310318ef4691a8230704f946ffb...,...,NaN,iOS,iOS 17.6.1,N,NaN,NaN,5.02,NaN,NaN,2024-11-09 09:44:41.372
1,2024-11-06,UA-110770460-3,WEB,5f29ad14c1f1785ea41698666b95c2bf469b4bf5122e45...,2024-11-06 22:22:12.875,2049144370.1730898977,2049144370.17308989771730898977,NaN,f6eec8e63cee2cf90165c6b3f68c1285d9ffedf7f8e134...,d8d5b1d15ce86752f1f310318ef4691a8230704f946ffb...,...,NaN,iOS,iOS 17.6.1,N,NaN,NaN,0.60,NaN,NaN,2024-11-09 09:44:41.372

### 메시지 전처리

In [5]:
msg = pd.read_csv('./raw/CUSTOMER_MSG.csv')
print(msg.shape)
msg.head(2)

(2229222, 8)

,STND_YMD,INCS_NO,MSG_SEND_CHN_CD,MSG_SEND_CHN_NM,MSG_SEND_OFR_CHN_CD,MSG_SEND_OFR_CHN_NM,MSG_SEND_CNT,ETL_PROC_DTTM
0,2024-11-13,5a188a7f5c9efb89d77ad565a1b5e4f7263812ce2c098b...,FT,카카오 친구톡,IN23080103A,이니스프리,1,2024-11-30 04:45:31.281
1,2024-11-13,2968941337eb215b09f9ff23cd7e0669b918dc3545fe7a...,FT,카카오 친구톡,IN23080103A,이니스프리,1,2024-11-30 04:45:31.281

In [6]:
msg_dtl = pd.read_csv('./raw/11월_친구톡utm.csv')
msg_dtl.head(2)

,저니,저니명,버전,발송타입,발송시간,본문,버튼
0,IN24112601S,IN24112601S_이니_광고정보수집안내_241126수기,1,알림톡,11-27-2024 5:06 PM,"[안내] 이니스프리\n광고성정보 수신동의 여부 안내\n\n고객님, 이니스프리를 이용...","{""button"":[{""name"":""채널 추가"", ""type"":""AC""}]}"
1,IN24111901S,IN24111901S_이니스프리_가입즉시 알림톡_테스트,7,알림톡,11-22-2024 10:03 AM,"[안내] 이니스프리 개인정보 이용내역 안내\n\n최소정님, 이니스프리를 이용해주셔서...","{""button"":[{""name"":""개인정보 이용내역 상세보기"", ""type"":""W..."

In [7]:
msg_merge = pd.merge(msg, msg_dtl, left_on='MSG_SEND_OFR_CHN_CD', right_on='저니', how='left')
print(msg_merge.shape)
msg_merge.head(2)

(2666241, 15)

,STND_YMD,INCS_NO,MSG_SEND_CHN_CD,MSG_SEND_CHN_NM,MSG_SEND_OFR_CHN_CD,MSG_SEND_OFR_CHN_NM,MSG_SEND_CNT,ETL_PROC_DTTM,저니,저니명,버전,발송타입,발송시간,본문,버튼
0,2024-11-13,5a188a7f5c9efb89d77ad565a1b5e4f7263812ce2c098b...,FT,카카오 친구톡,IN23080103A,이니스프리,1,2024-11-30 04:45:31.281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-13,2968941337eb215b09f9ff23cd7e0669b918dc3545fe7a...,FT,카카오 친구톡,IN23080103A,이니스프리,1,2024-11-30 04:45:31.281,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
msg_merge[msg_merge['저니'].notna()].to_csv('./data/MSG.csv')

In [8]:
cust_list = list(set(msg_merge['INCS_NO']))
cust_df = pd.DataFrame(cust_list, columns=['INCS_NO'])
print(cust_df.shape)
cust_df.head(2)

(607279, 1)

                                             INCS_NO
0  c1fee31145f73ed7a577e27496b1f08ce71c54fc962f17...
1  9de827087601bd04bab8c24ed3f04fe2011b2a66c70b53...

In [21]:
cust_df.to_csv('./data/CUST.csv')

In [9]:
log.shape

(3668294, 99)

In [12]:
log_sampl = pd.merge(log, cust_df, on='INCS_NO', how='inner')
print(log_sampl.shape)

(997147, 99)

In [19]:
log_sampl.to_csv('./data/LOG.csv')