In [2]:
import pandas as pd

In [3]:
log = pd.read_csv('./raw/LOG.csv')
print(log.shape)
log.head(2)

C:\Users\amore\AppData\Local\Temp\ipykernel_18160\1845494227.py:1: DtypeWarning: Columns (26,28,29,55,71,84) have mixed types. Specify dtype option on import or set low_memory=False.
  log = pd.read_csv('./raw/LOG.csv')

(10704736, 99)

,STND_YMD,SITE_ID,WEB_APP_CL_CD,LOG_SEQ,LOG_DTTM,GOOGLE_CID,SESS_ID,ADID,INCS_NO,SITE_MBR_ID,...,DVCE_MKT_NM,DVCE_OPRT_NM,DVCE_OPRT_VER,NEW_VISIT_YN,STORE_CD,INVN_ST_YN,SESS_SN_STAY_TIME,EXPS_RSLT_LIST,LIST_TP_NM,ETL_PROC_DTTM
0,2024-11-07,UA-110770460-3,APP,8f55d6120696525bac0623c65ca522ec5a88a38abd9de6...,2024-11-07 10:39:05.817,ebf9253d9f7379204a07514597c8d411,ebf9253d9f7379204a07514597c8d4111730943539,d0513607-69f7-459f-b174-11cbf0e37c98,ff6f3c293eff9383097780fd93f98eb80e4430d9c92f98...,e56a4801c6700a30ac9a41aa22de78da634c53a163836d...,...,Galaxy S20 FE 5G,Android,Android 13,N,NaN,NaN,2.16,NaN,NaN,2024-11-10 09:44:08.785
1,2024-11-07,UA-110770460-3,APP,127692ba29ecd10fdb1be52c2826eff72c54ac70776488...,2024-11-07 10:39:14.391,ebf9253d9f7379204a07514597c8d411,ebf9253d9f7379204a07514597c8d4111730943539,d0513607-69f7-459f-b174-11cbf0e37c98,ff6f3c293eff9383097780fd93f98eb80e4430d9c92f98...,e56a4801c6700a30ac9a41aa22de78da634c53a163836d...,...,Galaxy S20 FE 5G,Android,Android 13,N,NaN,NaN,1.92,NaN,NaN,2024-11-10 09:44:08.785

### 메시지 전처리

In [4]:
msg = pd.read_csv('./raw/CUSTOMER_MSG.csv')
print(msg.shape)
msg.head(2)

(2229222, 8)

,STND_YMD,INCS_NO,MSG_SEND_CHN_CD,MSG_SEND_CHN_NM,MSG_SEND_OFR_CHN_CD,MSG_SEND_OFR_CHN_NM,MSG_SEND_CNT,ETL_PROC_DTTM
0,2024-11-13,5a188a7f5c9efb89d77ad565a1b5e4f7263812ce2c098b...,FT,카카오 친구톡,IN23080103A,이니스프리,1,2024-11-30 04:45:31.281
1,2024-11-13,2968941337eb215b09f9ff23cd7e0669b918dc3545fe7a...,FT,카카오 친구톡,IN23080103A,이니스프리,1,2024-11-30 04:45:31.281

In [5]:
msg_dtl = pd.read_csv('./raw/11월_친구톡utm.csv')
msg_dtl.head(2)

,저니,저니명,버전,발송타입,발송시간,본문,버튼
0,IN24112601S,IN24112601S_이니_광고정보수집안내_241126수기,1,알림톡,11-27-2024 5:06 PM,"[안내] 이니스프리\n광고성정보 수신동의 여부 안내\n\n고객님, 이니스프리를 이용...","{""button"":[{""name"":""채널 추가"", ""type"":""AC""}]}"
1,IN24111901S,IN24111901S_이니스프리_가입즉시 알림톡_테스트,7,알림톡,11-22-2024 10:03 AM,"[안내] 이니스프리 개인정보 이용내역 안내\n\n최소정님, 이니스프리를 이용해주셔서...","{""button"":[{""name"":""개인정보 이용내역 상세보기"", ""type"":""W..."

In [7]:
msg_merge = pd.merge(msg, msg_dtl, left_on='MSG_SEND_OFR_CHN_CD', right_on='저니', how='left')
msg_merge['본문'] = msg_merge['본문'].astype(str)
msg_merge = msg_merge[~msg_merge['본문'].str.contains('\[안내\]')]
print(msg_merge.shape)
msg_merge.head(2)

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:3: SyntaxWarning: invalid escape sequence '\['
C:\Users\amore\AppData\Local\Temp\ipykernel_18160\3001881449.py:3: SyntaxWarning: invalid escape sequence '\['
  msg_merge = msg_merge[~msg_merge['본문'].str.contains('\[안내\]')]

(2468195, 15)

,STND_YMD,INCS_NO,MSG_SEND_CHN_CD,MSG_SEND_CHN_NM,MSG_SEND_OFR_CHN_CD,MSG_SEND_OFR_CHN_NM,MSG_SEND_CNT,ETL_PROC_DTTM,저니,저니명,버전,발송타입,발송시간,본문,버튼
0,2024-11-13,5a188a7f5c9efb89d77ad565a1b5e4f7263812ce2c098b...,FT,카카오 친구톡,IN23080103A,이니스프리,1,2024-11-30 04:45:31.281,NaN,NaN,NaN,NaN,NaN,nan,NaN
1,2024-11-13,2968941337eb215b09f9ff23cd7e0669b918dc3545fe7a...,FT,카카오 친구톡,IN23080103A,이니스프리,1,2024-11-30 04:45:31.281,NaN,NaN,NaN,NaN,NaN,nan,NaN

In [8]:
msg_merge[msg_merge['저니'].notna()].to_csv('./data/MSG.csv')

In [9]:
cust_list = list(set(msg_merge['INCS_NO']))
cust_df = pd.DataFrame(cust_list, columns=['INCS_NO'])
print(cust_df.shape)
cust_df.head(2)

(444198, 1)

                                             INCS_NO
0  7ebc7584876e506a7618884ba5b6a03369ebf06b61296b...
1  a9423975eac86a6858b402432653d80aa0a407ea20568f...

In [10]:
log_sampl = pd.merge(log, cust_df, on='INCS_NO', how='inner')
print(log_sampl.shape)

(3011584, 99)

In [11]:
log_sampl.to_csv('./data/LOG.csv')