In [11]:
import pandas as pd

### 메시지발송 시간, 재방문 여부에 따른 종속변수 코딩
* sess 이후 메시지 발송 이력이 없으면 -1
* sess 이후 메시지 발송 이력이 있고, 재방문을 했다면 1
* sess 이후 메시지 발송 이력이 있고, 재방문을 하지 않았다면 0
* 메시지 데이터 merge

In [12]:
sess = pd.read_csv('./data/cv_add.csv', index_col=0)
sess['LST_SESS_TIME'] = pd.to_datetime(sess['LST_SESS_TIME'])
print(sess.shape)
sess.head(2)

(77157, 16)

,SESS_ID,SRCH_EFRT,PRDV_CNT,CAT_CNT,SAMGE_PAGE_CNT,EVNT_CNT,INCS_NO,LST_SESS_TIME,AVG_DEPTH,day_off,SEX_CD,AVG_SAL_AMT,AGE_30,AGE_50,AGE_60,AGE_1020
1,000A204228DB4108A69885BF2BCA220E1730848747,70,13,1,23,70,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,2024-11-06 08:39:48.598,33.965517,1,1,18747.0,1,0,0,0
2,000A204228DB4108A69885BF2BCA220E1730887540,20,3,0,9,20,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,2024-11-06 19:08:59.950,10.000000,1,1,18747.0,1,0,0,0

In [4]:
msg = pd.read_csv('./data/msg_indicate.csv', index_col = 0)
msg['STND_YMD'] = pd.to_datetime(msg['STND_YMD'])
print(msg.shape)
msg.head(2)

(2380798, 6)

,STND_YMD,INCS_NO,msg_length,max_discount,emoji_count,time_pressure
421,2024-11-13,3ee6a62a6cd178a8c9247160fc0828ae92a5cc137d7bd1...,115,10.0,0,0
422,2024-11-13,3ee6a62a6cd178a8c9247160fc0828ae92a5cc137d7bd1...,116,10.0,0,0

In [5]:
sess_copy = sess.copy()

In [10]:
sess_copy[sess_copy['INCS_NO'] == sess_copy.iloc[0]['INCS_NO']]

,SESS_ID,SRCH_EFRT,PRDV_CNT,CAT_CNT,SAMGE_PAGE_CNT,EVNT_CNT,INCS_NO,LST_SESS_TIME,AVG_DEPTH,day_off,SEX_CD,AVG_SAL_AMT,AGE_30,AGE_50,AGE_60,AGE_1020
1,000A204228DB4108A69885BF2BCA220E1730848747,70,13,1,23,70,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,2024-11-06 08:39:48.598,33.965517,1,1,18747.0,1,0,0,0
2,000A204228DB4108A69885BF2BCA220E1730887540,20,3,0,9,20,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,2024-11-06 19:08:59.950,10.000000,1,1,18747.0,1,0,0,0

In [6]:
msg[msg['INCS_NO'] == sess_copy.iloc[0]['INCS_NO']]

,STND_YMD,INCS_NO,msg_length,max_discount,emoji_count,time_pressure
375017,2024-09-20,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,47,0.0,1,0
553995,2024-10-17,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,55,40.0,0,0
692250,2024-09-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,58,10.0,0,0
773975,2024-10-05,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,68,50.0,0,0
1040249,2024-09-08,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,49,33.0,2,0
1653659,2024-10-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,262,40.0,1,0
1653660,2024-10-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,228,40.0,1,0
1653661,2024-10-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,231,40.0,1,0
1653662,2024-10-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,251,40.0,1,0
1653663,2024-10-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,255,40.0,1,0
1861145,2024-10-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,74,64.0,1,0
2004642,2024-10-11,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,118,50.0,0,0
2533169,2024-09-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,262,40.0,1,0
2533170,2024-09-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,228,40.0,1,0
2533171,2024-09-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,231,40.0,1,0
2533172,2024-09-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,251,40.0,1,0
2533173,2024-09-28,51dea90cd3bb8eb26f2580e7891ebb2d38e1d820b8b85a...,255,40.0,1,0

In [7]:
sess = sess[:200]

In [ ]:
# scroll데이터 붙이기
# 고객 개인정보 붙이기

In [ ]:
sess.drop

In [ ]:
sess.to_csv('./data/sess')