In [1]:
import pandas as pd

In [80]:
df = pd.read_csv('./data/final.csv', index_col=0)
df.head(2)

,y,msg_length,max_discount,emoji_count,time_pressure,SRCH_EFRT,PRDV_CNT,CAT_CNT,SAMGE_PAGE_CNT,EVNT_CNT,AVG_DEPTH,day_off,SEX_CD,AVG_SAL_AMT,AGE_30,AGE_50,AGE_60,AGE_1020
0,0,30,32.0,0,0,6,2,0,2,6,24.285714,1,1,21490.0,0,0,0,0
1,0,41,0.0,0,0,15,4,0,4,15,16.666667,0,1,26085.0,0,1,0,0

In [81]:
df.columns

Index(['y', 'msg_length', 'max_discount', 'emoji_count', 'time_pressure',
       'SRCH_EFRT', 'PRDV_CNT', 'CAT_CNT', 'SAMGE_PAGE_CNT', 'EVNT_CNT',
       'AVG_DEPTH', 'day_off', 'SEX_CD', 'AVG_SAL_AMT', 'AGE_30', 'AGE_50',
       'AGE_60', 'AGE_1020'],
      dtype='object')

In [88]:
df = df[['y', 'msg_length', 'max_discount', 'emoji_count', 'time_pressure',
       'SRCH_EFRT', 'CAT_CNT',
       'AVG_DEPTH', 'day_off']]

In [89]:
df.head(2)

,y,msg_length,max_discount,emoji_count,time_pressure,SRCH_EFRT,CAT_CNT,AVG_DEPTH,day_off
0,0,30,32.0,0,0,6,0,24.285714,1
1,0,41,0.0,0,0,15,0,16.666667,0

In [111]:
df_copy = df.copy()


def remove_outliers(df, columns):
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = 0
        upper_bound = Q3 + 1.5 * IQR
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
    return df

df = remove_outliers(df, ["SRCH_EFRT", "CAT_CNT", "AVG_DEPTH"])

In [113]:
import statsmodels.api as sm

# 특징 변수와 종속 변수 분리
X = df_copy.drop(columns=['y'])  # 'y'는 종속 변수 열 이름입니다.
y = df_copy['y']

# 상수항 추가
X = sm.add_constant(X)


# 로지스틱 회귀 모델 생성 및 학습
model = sm.Logit(y, X)
result = model.fit()

result.summary()

Optimization terminated successfully.
         Current function value: 0.132141
         Iterations 8

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:               896265
Model:                          Logit   Df Residuals:                   896256
Method:                           MLE   Df Model:                            8
Date:                Wed, 26 Feb 2025   Pseudo R-squ.:                 0.03225
Time:                        21:38:28   Log-Likelihood:            -1.1843e+05
converged:                       True   LL-Null:                   -1.2238e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -3.2216      0.018   -176.436      0.000      -3.257      -3.186
msg_length        0.0008   7.74e-05     10.391      0.000       0.001       0.001
max_discount     -0.0189      0.000    -59.875      0.000      -0.019      -0.018
emoji_count       0.6074      0.015     39.568      0.000       0.577       0.637
time_pressure     0.7024      0.025     27.603      0.000       0.653       0.752
SRCH_EFRT        -0.0014      0.001     -1.257      0.209      -0.004       0.001
CAT_CNT          -0.0095      0.010     -0.910      0.363      -0.030       0.011
AVG_DEPTH         0.0008      0.000      1.861      0.063   -4.16e-05       0.002
day_off           0.0043      0.013      0.342      0.732      -0.020       0.029
=================================================================================
"""

In [114]:
import statsmodels.api as sm

# 특징 변수와 종속 변수 분리
X = df.drop(columns=['y'])  # 'y'는 종속 변수 열 이름입니다.
y = df['y']

# 상수항 추가
X = sm.add_constant(X)


# 로지스틱 회귀 모델 생성 및 학습
model = sm.Logit(y, X)
result = model.fit()

result.summary()

Optimization terminated successfully.
         Current function value: 0.131802
         Iterations 8

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:               812960
Model:                          Logit   Df Residuals:                   812951
Method:                           MLE   Df Model:                            8
Date:                Wed, 26 Feb 2025   Pseudo R-squ.:                 0.03234
Time:                        21:38:49   Log-Likelihood:            -1.0715e+05
converged:                       True   LL-Null:                   -1.1073e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -3.2329      0.020   -164.071      0.000      -3.272      -3.194
msg_length        0.0008   8.16e-05      9.864      0.000       0.001       0.001
max_discount     -0.0190      0.000    -57.281      0.000      -0.020      -0.018
emoji_count       0.6016      0.016     37.162      0.000       0.570       0.633
time_pressure     0.7121      0.027     26.716      0.000       0.660       0.764
SRCH_EFRT        -0.0018      0.001     -1.326      0.185      -0.004       0.001
CAT_CNT           0.0149      0.012      1.198      0.231      -0.009       0.039
AVG_DEPTH         0.0007      0.000      1.484      0.138      -0.000       0.002
day_off           0.0192      0.013      1.456      0.145      -0.007       0.045
=================================================================================
"""

In [107]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

# 상관 계수 행렬 계산
corr_matrix = df.corr().abs()

# 상관 계수가 높은 변수 찾기
high_corr_var = np.where(corr_matrix > 0.9)
high_corr_var = [(corr_matrix.index[x], corr_matrix.columns[y]) for x, y in zip(*high_corr_var) if x != y and x < y]

# 높은 상관 관계를 갖는 변수 출력
print("상관 관계가 높은 변수들:", high_corr_var)

상관 관계가 높은 변수들: []