In [1]:
import pandas as pd

In [49]:
control = pd.read_csv('./data/control_sample.csv', index_col=0)
print(control.shape)

(107340, 13)

In [50]:
sm1 = pd.read_csv('./data/sample1.csv', index_col=0)
print(sm1.shape)
sm1.head(2)

(500000, 21)

,y,msg_length,max_discount,emoji_count,personalized,time_pressure,SRCH_EFRT,PRDV_CNT,CAT_CNT,SAMGE_PAGE_CNT,...,AVG_DEPTH,day_off,SEX_CD,AVG_SAL_AMT,AGE_30,AGE_50,AGE_60,AGE_1020,WEEKDAY,WEEKEND
0,0,30,32.0,0,0,0,6,2,0,2,...,24.285714,1,1,21490.0,0,0,0,0,4,0
1,0,41,0.0,0,0,0,15,4,0,4,...,16.666667,0,1,26085.0,0,1,0,0,6,1

In [51]:
sm2 = pd.read_csv('./data/sample2.csv', index_col=0)
print(sm2.shape)
sm2.head(2)

(548036, 21)

,y,msg_length,max_discount,emoji_count,personalized,time_pressure,SRCH_EFRT,PRDV_CNT,CAT_CNT,SAMGE_PAGE_CNT,...,AVG_DEPTH,day_off,SEX_CD,AVG_SAL_AMT,AGE_30,AGE_50,AGE_60,AGE_1020,WEEKDAY,WEEKEND
500000,0,43,0.0,0,0,0,4,1,0,2,...,41.111111,0,1,290.322812,0,1,0,0,4,0
500001,0,43,0.0,0,0,0,4,1,0,2,...,50.909091,0,1,290.322812,0,1,0,0,5,1

In [52]:
treat = pd.concat([sm1, sm2])
print(treat.shape)
treat.head(2)

(1048036, 21)

,y,msg_length,max_discount,emoji_count,personalized,time_pressure,SRCH_EFRT,PRDV_CNT,CAT_CNT,SAMGE_PAGE_CNT,...,AVG_DEPTH,day_off,SEX_CD,AVG_SAL_AMT,AGE_30,AGE_50,AGE_60,AGE_1020,WEEKDAY,WEEKEND
0,0,30,32.0,0,0,0,6,2,0,2,...,24.285714,1,1,21490.0,0,0,0,0,4,0
1,0,41,0.0,0,0,0,15,4,0,4,...,16.666667,0,1,26085.0,0,1,0,0,6,1

In [53]:
control_counts = control['y'].value_counts()
treat_counts = treat['y'].value_counts()

# 빈도표 결합
contingency_table = pd.DataFrame({'control': control_counts, 'treat': treat_counts}).fillna(0)
print(contingency_table)

   control    treat
y
0   104803  1016133
1     2537    31903

In [54]:
from scipy.stats import chi2_contingency

# chi2 검정 수행
chi2, p, dof, expected = chi2_contingency(contingency_table)
print('Chi2 통계량:', chi2)
print('p-value:', p)

Chi2 통계량: 155.70070336238223
p-value: 9.841714517159901e-36